### ISSUE TITLE
Check for: Running Python in Android Studio

### ISSUE THREAD

**Issue by sverbach** [sverbach/m3ts#1]
Multiple Tracking libraries in python -> possible to run python in android studio?

**Comment by sverbach** [comment]
Done, wenn:

- Python Project (Hello World) in Android Studio zum laufen bringen - oder eben nicht

**Comment by VulcanCascade** [comment]
Following methods were found to run python code with java/android:

- Kivy - Cross Platform Python Framework (but packaging for Android only on Linux VM) 
https://kivy.org/

- QPython, Kivy - Launchers to run on Android (no packaging needed but code can only be run on launcher) https://www.qpython.com/

- python-for-android - Packaging tool for python on android (extremely hard to run on Windows)
https://pypi.org/project/python-for-android/

- Other solutions to run python in java without 3rd party libs (for example start a process which runs python code and so on)
https://www.baeldung.com/java-working-with-python
