### ISSUE TITLE
Event Detection: Ball out of Frame

### ISSUE THREAD

**Issue by sverbach** [sverbach/m3ts#12]
-> Flag nach n-Frames ausser Bild (Gibt einen Punkt)

**Comment by chrisslazzz** [comment]
Die Out of Frame Detection muss bei der Matchlogik implementiert werden, da der EventDetector nur aufgerufen wird, wenn wirklich ein Ball detected wurde. Um dies dann bei der Matchlogik einfacher implementieren zu können, wird hier ein anderes Event ausgelöst --> ballNearlyOutOfFrame
Wenn dieses Event ausgelöst wird, kann in der Matchlogik die vergangene Zeit seit der letzten Detection berechnet werden und dementsprechend entscheiden ob ein Punkt vergeben werden soll.
