### ISSUE TITLE
Display benutzen um Tischecken zu selektieren

### ISSUE THREAD

**Issue by sverbach** [sverbach/m3ts#32]
bytearray to base64: https://stackoverflow.com/questions/36492084/how-to-convert-an-image-to-base64-string-in-java
-> send base64 string in json 
-> then use that string in display to create bitmap
base64 to image/file: https://stackoverflow.com/questions/23979842/convert-base64-string-to-image

**Comment by VulcanCascade** [comment]
Match-Start Prozess mit Display als Tischecken-Selektor und QR-Code für Config-Übermittlung:
1. Camera: camera wählen und aufstellen
2. Display: display wählen
3. Display: Konfigurationen auswählen: matchType, serverSide, 
(in Zukunft auch noch playerLeft and playerRight vom Profil laden und wählen)
4. Display: erstellt QR-code
5. Camera: scannt QR-code und konfiguriert Game
6. Display: bietet einen Button mit "Tischfoto erstellen"
7. Camera: erstellt Foto on Button click on Display und schickt dieses an Display
8. Display: selektiert Corners und schickt Bild an Camera
9. Camera: selektiert Corners
